name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Corrected syntax for using checkout action
      - uses: actions/checkout@v4
      
      # Corrected syntax for setting up Node.js
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Install dependencies
      - run: npm ci

      # Build and run tests
      - run: npm run build --if-present
      - run: npm test